CREATE DATABASE LOGIN1;

USE LOGIN1;

CREATE TABLE PERSONA(
USUARIO VARCHAR(100) PRIMARY KEY,
CONTRASEÑA VARCHAR(100),
ROLL VARCHAR(100),
); 

SELECT * FROM PERSONA;
INSERT INTO PERSONA VALUES ('JORGE','777','CLIENTE');
INSERT INTO PERSONA VALUES ('JOSEPH','999','ADMINISTRADOR');
INSERT INTO PERSONA VALUES ('CAROLINA','123','SECRETARIA');

